import type { InterviewQuestionSeed } from "./types.js";

const now = Date.now();

export const elasticsearchQuestions: InterviewQuestionSeed[] = [
  {
    id: "iq_es_1",
    area: "database",
    difficulty: "junior",
    category: "Elasticsearch",
    question: "How does Elasticsearch's inverted index enable fast full-text search?",
    answer: "An inverted index maps each unique token to the list of documents containing it. During indexing, text is passed through an analyzer (tokenize → lowercase → stem → remove stopwords), producing tokens stored in the inverted index. At query time, the search term is analyzed with the same analyzer and looked up in the index — an O(1) hash lookup, not a table scan. This is why Elasticsearch can search millions of documents in milliseconds, unlike LIKE '%term%' SQL queries which force full table scans.",
    tags: ["elasticsearch", "elastic", "opensearch", "search", "database"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_es_2",
    area: "database",
    difficulty: "junior",
    category: "Elasticsearch",
    question: "What is the difference between text and keyword field types in Elasticsearch?",
    answer: "text: analyzed field — text is tokenized, lowercased, and stemmed before indexing. Used for full-text search (match query). Cannot be sorted or used in aggregations directly. keyword: not analyzed — stored as-is (exact value). Used for exact match (term query), sorting, and aggregations (terms agg, cardinality). Best practice: for searchable string fields, map as text with a .keyword sub-field to get both full-text search and exact aggregations. Dynamic mapping creates both automatically.",
    tags: ["elasticsearch", "elastic", "opensearch", "search", "database"],
    createdAt: now,
  },
  {
    id: "iq_es_3",
    area: "database",
    difficulty: "junior",
    category: "Elasticsearch",
    question: "What are shards and replicas in Elasticsearch and why do they matter?",
    answer: "Shards: an index is split into N primary shards, each a self-contained Lucene index. Shards enable horizontal scaling — distributed across nodes for parallel writes and reads. The number of primary shards is set at index creation and cannot be changed without reindexing. Replicas: copies of primary shards on different nodes. They serve read requests (increasing throughput) and provide fault tolerance (if a primary node fails, a replica is promoted). Aim for shard sizes of 10–50 GB for optimal performance.",
    tags: ["elasticsearch", "elastic", "opensearch", "search", "database"],
    createdAt: now,
  },
  {
    id: "iq_es_4",
    area: "database",
    difficulty: "mid",
    category: "Elasticsearch",
    question: "Explain the difference between query context and filter context in Elasticsearch.",
    answer: "Query context: computes a relevance _score for each matching document (BM25 algorithm). Used with match, multi_match, query_string. Results ranked by relevance. Filter context: boolean match/no-match — no scoring. Used with term, range, exists inside a bool.filter or bool.must_not clause. Filter results are cached by Elasticsearch at the shard level — significantly faster for repeated filters (e.g., status: 'active'). Rule: use filter context for exact conditions; use query context for relevance-scored full-text.",
    tags: ["elasticsearch", "elastic", "opensearch", "search", "database"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_es_5",
    area: "database",
    difficulty: "mid",
    category: "Elasticsearch",
    question: "How do Elasticsearch aggregations work and what are the main types?",
    answer: "Aggregations compute analytics over a matched set of documents. Three families: 1. Bucket aggregations — group documents into buckets: terms (by field value), date_histogram (time intervals), range (custom ranges), nested (for nested objects). 2. Metric aggregations — compute values: avg, sum, min, max, cardinality (HyperLogLog distinct count), percentiles. 3. Pipeline aggregations — operate on other aggregation outputs: moving_avg, derivative, bucket_sort. Aggregations compose: each bucket can contain sub-aggregations for multi-level analytics (e.g., sales per month per product).",
    tags: ["elasticsearch", "elastic", "opensearch", "search", "database"],
    createdAt: now,
  },
  {
    id: "iq_es_6",
    area: "database",
    difficulty: "mid",
    category: "Elasticsearch",
    question: "What is an Elasticsearch analyzer and how do you customize one?",
    answer: "An analyzer processes text during indexing and search. Three components: 1. char_filter: pre-process text (e.g., HTML stripping, character mapping). 2. tokenizer: split text into tokens (standard, whitespace, ngram, edge_ngram). 3. token_filter: transform tokens (lowercase, stemmer, synonyms, stopwords, asciifolding). Custom analyzer example: edge_ngram tokenizer for autocomplete, synonym filter for domain vocabulary, asciifolding to normalize accented characters. Use GET index/_analyze to debug how text is tokenized before deploying a mapping.",
    tags: ["elasticsearch", "elastic", "opensearch", "search", "database"],
    createdAt: now,
  },
  {
    id: "iq_es_7",
    area: "database",
    difficulty: "senior",
    category: "Elasticsearch",
    question: "How do you perform a zero-downtime reindex in Elasticsearch?",
    answer: "Reindexing is required when changing field mappings (cannot update analyzed field types in place). Zero-downtime approach: 1. Create new index with updated mappings. 2. Use POST _reindex to copy documents from old to new index (background, can run in parallel). 3. While reindexing, new writes should go to both old and new indexes (dual-write or use an alias that points to both). 4. Once reindex completes, switch the read alias to point to the new index atomically using POST _aliases with a remove+add action. 5. Remove the old index. Index aliases are essential for this pattern.",
    tags: ["elasticsearch", "elastic", "opensearch", "search", "database"],
    favorite: true,
    createdAt: now,
  },
];
