import type { InterviewQuestionSeed } from "./types.js";

const now = Date.now();

export const sqlServerQuestions: InterviewQuestionSeed[] = [
  {
    id: "iq_ss_1",
    area: "database",
    difficulty: "junior",
    category: "SQL Server",
    question: "What is the difference between a clustered and non-clustered index in SQL Server?",
    answer: "Clustered index: determines the physical storage order of rows in the table — there can only be one (usually the primary key). The leaf level of the clustered index IS the data. Non-clustered index: a separate B-Tree structure with pointers (row locators) to the actual data rows. A table can have up to 999 non-clustered indexes. For a heap (no clustered index), the row locator is a row ID; for a clustered table it is the clustering key.",
    tags: ["sqlserver", "mssql", "tsql", "sql", "database"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_ss_2",
    area: "database",
    difficulty: "junior",
    category: "SQL Server",
    question: "What is T-SQL and how does it differ from standard ANSI SQL?",
    answer: "T-SQL (Transact-SQL) is Microsoft's proprietary extension of ANSI SQL used in SQL Server and Azure SQL. Additions: procedural constructs (IF/ELSE, WHILE, TRY/CATCH), stored procedures, user-defined functions, triggers, TOP N clause (vs LIMIT), GETDATE() (vs NOW()), IDENTITY columns (vs AUTO_INCREMENT), table variables, temp tables (#temp), and locking hints (NOLOCK, UPDLOCK, HOLDLOCK).",
    tags: ["sqlserver", "mssql", "tsql", "sql", "database"],
    createdAt: now,
  },
  {
    id: "iq_ss_3",
    area: "database",
    difficulty: "mid",
    category: "SQL Server",
    question: "What is READ_COMMITTED_SNAPSHOT ISOLATION (RCSI) and why should you enable it?",
    answer: "By default, SQL Server's READ COMMITTED isolation uses shared locks — readers block writers and writers block readers. RCSI changes READ COMMITTED to use row versioning stored in tempdb: readers see a consistent snapshot of data as of the start of the statement without taking shared locks. This eliminates most blocking and deadlocks in OLTP systems without sacrificing data consistency. Enable with: ALTER DATABASE [db] SET READ_COMMITTED_SNAPSHOT ON.",
    tags: ["sqlserver", "mssql", "tsql", "sql", "database"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_ss_4",
    area: "database",
    difficulty: "mid",
    category: "SQL Server",
    question: "How do you identify and resolve a parameter sniffing problem in SQL Server?",
    answer: "Parameter sniffing: SQL Server compiles a stored procedure's execution plan based on the first parameter values it sees. If those values are atypical (e.g., returning 1 row when most calls return 100k rows), future calls with typical parameters use a suboptimal cached plan. Solutions: OPTION (RECOMPILE) forces per-execution compilation; OPTION (OPTIMIZE FOR UNKNOWN) uses average statistics; local variable assignment within the proc forces fresh statistics lookup; sp_recompile clears the cached plan.",
    tags: ["sqlserver", "mssql", "tsql", "sql", "database"],
    createdAt: now,
  },
  {
    id: "iq_ss_5",
    area: "database",
    difficulty: "mid",
    category: "SQL Server",
    question: "What are Window Functions in SQL Server and give a practical example?",
    answer: "Window functions perform calculations across a set of rows related to the current row without collapsing results like GROUP BY. Syntax: FUNCTION() OVER (PARTITION BY col ORDER BY col ROWS BETWEEN ...). Examples: ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC) assigns rank within each dept; LAG(salary, 1) OVER (ORDER BY hire_date) accesses the previous row's salary; SUM(amount) OVER (PARTITION BY month) computes a running total. Essential for pagination, ranking, and time-series analysis.",
    tags: ["sqlserver", "mssql", "tsql", "sql", "database"],
    createdAt: now,
  },
  {
    id: "iq_ss_6",
    area: "database",
    difficulty: "senior",
    category: "SQL Server",
    question: "Explain SQL Server Always On Availability Groups and how they provide HA/DR.",
    answer: "Always On AG is SQL Server's enterprise HA/DR solution. Architecture: one primary replica (read/write) + up to 8 secondary replicas. Log records are sent to secondaries via the AG endpoint. Synchronous commit: secondary confirms before primary commits — zero data loss, enables automatic failover. Asynchronous commit: better performance, potential data loss, manual failover only. Clients connect via the AG Listener (virtual network name) — transparent failover. Readable secondaries offload reporting queries from primary.",
    tags: ["sqlserver", "mssql", "tsql", "sql", "database"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_ss_7",
    area: "database",
    difficulty: "senior",
    category: "SQL Server",
    question: "How do you use execution plans to diagnose slow queries in SQL Server?",
    answer: "Enable actual execution plan in SSMS (Ctrl+M) or use SET STATISTICS IO/TIME ON. Key operators to investigate: Clustered Index Scan / Table Scan (full scans — check for missing indexes), Key Lookup (non-clustered index found the row but needed to fetch more columns — add INCLUDE columns), Hash Match on large inputs (memory spill to tempdb — look for yellow warning icon), Nested Loops on large sets (consider Hash Join). sys.dm_exec_query_stats + sys.dm_exec_sql_text identifies the most expensive queries by total CPU or I/O.",
    tags: ["sqlserver", "mssql", "tsql", "sql", "database"],
    createdAt: now,
  },
];
